server:
  port: 9000

spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: postgres123
    url: jdbc:postgresql://db-chatapp-user.csrwqbdtsudq.us-east-1.rds.amazonaws.com/chatappdb
    hikari:
      max-lifetime: 600000
    dbcp2:
      test-while-idle: true
      test-on-borrow: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true